version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
    volumes:
      # So that Traefik can listen to the Docker events
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=pm
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
